# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    default_config: default
    configs:
        default:
            toolbar:
            - ["Styles", "Format"]
            - ["Bold", "Italic", "-", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "-", "Link", "Unlink", "Anchor", "-", "NumberedList", 'BulletedList', '-', 'Outdent', 'Indent']
            - ["Image", 'Table', 'HorizontalRule', 'SpecialChar', 'Smiley']
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
