# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~
        carousel_header :
            quality : 75
        thumbnail :
            quality : 50
            filters :
                thumbnail  : { size : [350, 270] }
