pi_crud:
    entities:
        event:
            templates:
                item_default: 'event/item.html.twig'
        map:
            templates:
                item_default: 'map/item.html.twig'
    templates:
        field_private: 'partials/fields/field_private.html.twig'
        field_promote: 'partials/fields/field_promote.html.twig'
        field_file: 'partials/fields/field_file.html.twig'
        field_files: 'partials/fields/field_files.html.twig'
        field_circuits: 'partials/fields/field_circuits.html.twig'
