home:
    path:     /
    defaults: { _controller: HomeBundle:Home:index }

about:
    path:     /about
    defaults: { _controller: HomeBundle:Home:about }

help:
    path:     /help
    defaults: { _controller: HomeBundle:Home:help }

register:
    path:     /register
    defaults: { _controller: HomeBundle:Register:register }

login:
    path:     /login
    defaults: { _controller: HomeBundle:Login:login }

logout:
    path:     /logout
    defaults: { _controller: HomeBundle:Login:logout }
