services:
#    home.example:
#        class: HomeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    manager.user:
        class: Bundle\HomeBundle\Manager\UserManager
        arguments: ['@doctrine.orm.entity_manager', '@security.password_encoder', '@security.token_storage']
