<?php

namespace AppBundle\Repository;

/**
 * CircuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitRepository extends \Doctrine\ORM\EntityRepository
{
}
