<?php

namespace AppBundle\Repository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
  public function findFutureCourse(){
    return $this->createQueryBuilder('c')
        ->where('c.date >= :date')
        ->setParameter('date', new \Datetime(date('d-m-Y')))
        ->orderBy('c.date', 'ASC')
        ->getQuery()
        ->getResult();
  }
}
