<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
  public function findFutureCourse(){
    return $this->createQueryBuilder('c')
        ->where('c.date >= :date')
        ->setParameter('date', new \Datetime(date('d-m-Y')))
        ->orderBy('c.date', 'ASC')
        ->getQuery()
        ->getResult();
  }

  public function findCourseWhereUserIsRegistered(User $user)
  {
    return $this->createQueryBuilder('c')
        ->select('c')
        ->from('AppBundle\Entity\Inscrit', 'i')
        ->where('c.date >= :date')
        ->andWhere('i.course = c.id')
        ->andWhere('i.user = :user')
        ->setParameters(array('date' => new \Datetime(date('d-m-Y')), 'user' => $user->getId()))
        ->orderBy('c.date', 'ASC')
        ->getQuery()
        ->getResult();
  }
}
