definition:
    resource: "@DefinitionBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    resource: '@HomeBundle/Resources/config/routing.yml'

club:
    resource: '@ClubBundle/Resources/config/routing.yml'

parcours:
    resource: '@ParcoursBundle/Resources/config/routing.yml'

calendrier:
    resource: '@CalendarBundle/Resources/config/routing.yml'

admin:
    resource: '@AdminBundle/Resources/config/routing.yml'
