# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.file.twig.extension:
          class: Services\FileExtension
          arguments: ['@kernel']
          tags:
            - { name: twig.extension }

  app.date.twig.extension:
          class: Services\DateExtension
          arguments: []
          tags:
            - { name: twig.extension }

  app.array.twig.extension:
          class: Services\ArrayExtension
          arguments: []
          tags:
            - { name: twig.extension }

  manager.actualite:
      class: Manager\ActualiteManager
      arguments: ['@doctrine.orm.entity_manager', '@session']

  manager.course:
      class: Manager\CourseManager
      arguments: ['@doctrine.orm.entity_manager', '@session']

  manager.type:
      class: Manager\TypeManager
      arguments: ['@doctrine.orm.entity_manager', '@session']

  manager.role:
      class: Manager\RoleManager
      arguments: ['@doctrine.orm.entity_manager', '@session']

  manager.tarif:
      class: Manager\TarifManager
      arguments: ['@doctrine.orm.entity_manager', '@session']

  manager.contact:
      class: Manager\ContactManager
      arguments: ['@doctrine.orm.entity_manager', '@session']

  manager.carte:
      class: Manager\CarteManager
      arguments: ['@doctrine.orm.entity_manager', '@session']

  manager.user:
      class: Manager\UserManager
      arguments: ['@doctrine.orm.entity_manager', '@session', '@security.password_encoder', '@security.token_storage']

  manager.inscrit:
      class: Manager\InscritManager
      arguments: ['@doctrine.orm.entity_manager', '@session', '@security.token_storage', '@security.authorization_checker']
