# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.file.twig.extension:
          class: Services\FileExtension
          arguments: ['@kernel']
          tags:
            - { name: twig.extension }

  app.date.twig.extension:
          class: Services\DateExtension
          arguments: []
          tags:
            - { name: twig.extension }

  app.array.twig.extension:
          class: Services\ArrayExtension
          arguments: []
          tags:
            - { name: twig.extension }

  manager.default:
      abstract:  true
      class: Manager\DefaultManager
      arguments: ['@doctrine.orm.entity_manager', '@session', '@security.token_storage']

  manager.actualite:
      class: Manager\ActualiteManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\Actualite']]

  manager.course:
      class: Manager\CourseManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\Course']]

  manager.type:
      class: Manager\TypeManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\Type']]

  manager.role:
      class: Manager\RoleManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\Role']]

  manager.tarif:
      class: Manager\TarifManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\Tarif']]

  manager.contact:
      class: Manager\ContactManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\Contact']]

  manager.carte:
      class: Manager\CarteManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\Carte']]

  manager.document:
      class: Manager\DocumentManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\Document']]

  manager.user:
      class: Manager\UserManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\User']]
          - [setPasswordEncoder, ['@security.password_encoder']]

  manager.inscrit:
      class: Manager\InscritManager
      parent: manager.default
      calls:
          - [setEntityNamespace, ['Entity\Inscrit']]
