# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.file.twig.extension:
          class: Services\FileExtension
          arguments: ['@kernel']
          tags:
            - { name: twig.extension }

  app.date.twig.extension:
          class: Services\DateExtension
          arguments: ['@kernel']
          tags:
            - { name: twig.extension }
