<?php

namespace Repository;

/**
* BaseRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{
}
