<?php

namespace Repository;

/**
 * CartesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartesRepository extends \Doctrine\ORM\EntityRepository
{
  public function findCartes(){
    return $this->createQueryBuilder('c')
        ->orderBy('c.nom', 'ASC')
        ->getQuery()
        ->getResult();
  }
}
