<?php

namespace Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
  public function findContact(){
    return $this->createQueryBuilder('c')
        ->where('c.fonction != \'Webmaster\'')
        ->orderBy('c.fonction', 'ASC')
        ->getQuery()
        ->getResult();
  }
}
