<?php

namespace Repository;

/**
 * user_attachedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAttachedRepository extends \Doctrine\ORM\EntityRepository
{
}
