club_presentation:
    path:     /club/presentation
    defaults: { _controller: ClubBundle:Club:presentation }

club_ecole:
    path:     /club/ecole
    defaults: { _controller: ClubBundle:Club:ecole }

club_rejoindre:
    path:     /club/rejoindre
    defaults: { _controller: ClubBundle:Club:rejoindre }

club_contact:
    path:     /club/contact
    defaults: { _controller: ClubBundle:Club:contact }
