calendrier:
    path:     /calendrier
    defaults: { _controller: CalendarBundle:Calendar:calendar }

course:
    path:     /calendrier/{id}/
    defaults: { _controller: CalendarBundle:Calendar:course }
