services:
#    calendar.example:
#        class: CalendarBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    manager.course:
        class: Bundle\CalendarBundle\Manager\CourseManager
        arguments: ['@doctrine.orm.entity_manager']

    manager.inscrit:
        class: Bundle\CalendarBundle\Manager\InscritManager
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@security.authorization_checker', '@session']
