admin_home:
    path:     /admin
    defaults: { _controller: AdminBundle:Admin:index }

#Actualite
admin_actualite:
    path:       /admin/actualite
    defaults:   { _controller: AdminBundle:AdminActualite:index }

actualite_add:
    path:     /admin/actualite/add
    defaults: { _controller: AdminBundle:AdminActualite:add }

actualite_delete:
    path:     /admin/actualite/delete
    defaults: { _controller: AdminBundle:AdminActualite:delete }

actualite_form:
    path:     /admin/actualite/form
    defaults: { _controller: AdminBundle:AdminActualite:form }

#Course
admin_course:
    path:       /admin/course
    defaults:   { _controller: AdminBundle:AdminCourse:index }

course_add:
    path:     /admin/course/add
    defaults: { _controller: AdminBundle:AdminCourse:add }

course_delete:
    path:     /admin/course/delete
    defaults: { _controller: AdminBundle:AdminCourse:delete }

course_form:
    path:     /admin/course/form
    defaults: { _controller: AdminBundle:AdminCourse:form }

#Type
admin_type_course:
    path:       /admin/data/type
    defaults:   { _controller: AdminBundle:AdminTypeCourse:index }

type_course_add:
    path:     /admin/data/type/add
    defaults: { _controller: AdminBundle:AdminTypeCourse:add }

type_course_delete:
    path:     /admin/data/type/delete
    defaults: { _controller: AdminBundle:AdminTypeCourse:delete }

type_course_form:
    path:     /admin/data/type/form
    defaults: { _controller: AdminBundle:AdminTypeCourse:form }
