admin_home:
    path:     /admin
    defaults: { _controller: AdminBundle:Admin:index }

#Actualite
admin_actualite:
    path:       /admin/actualite
    defaults:   { _controller: AdminBundle:AdminActualite:index }

actualite_add:
    path:     /admin/actualite/add
    defaults: { _controller: AdminBundle:AdminActualite:add }

actualite_delete:
    path:     /admin/actualite/delete
    defaults: { _controller: AdminBundle:AdminActualite:delete }

actualite_form:
    path:     /admin/actualite/form
    defaults: { _controller: AdminBundle:AdminActualite:form }

#Course
admin_course:
    path:       /admin/course
    defaults:   { _controller: AdminBundle:AdminCourse:index }

course_add:
    path:     /admin/course/add
    defaults: { _controller: AdminBundle:AdminCourse:add }

course_delete:
    path:     /admin/course/delete
    defaults: { _controller: AdminBundle:AdminCourse:delete }

course_form:
    path:     /admin/course/form
    defaults: { _controller: AdminBundle:AdminCourse:form }

#Type
admin_type_course:
    path:       /admin/config/type
    defaults:   { _controller: AdminBundle:AdminTypeCourse:index }

type_course_add:
    path:     /admin/config/type/add
    defaults: { _controller: AdminBundle:AdminTypeCourse:add }

type_course_delete:
    path:     /admin/config/type/delete
    defaults: { _controller: AdminBundle:AdminTypeCourse:delete }

type_course_form:
    path:     /admin/config/type/form
    defaults: { _controller: AdminBundle:AdminTypeCourse:form }

#Role
admin_role:
    path:       /admin/config/role
    defaults:   { _controller: AdminBundle:AdminRole:index }

role_add:
    path:     /admin/config/role/add
    defaults: { _controller: AdminBundle:AdminRole:add }

role_delete:
    path:     /admin/config/role/delete
    defaults: { _controller: AdminBundle:AdminRole:delete }

role_form:
    path:     /admin/config/role/form
    defaults: { _controller: AdminBundle:AdminRole:form }

#Tarif
admin_tarif:
    path:       /admin/config/tarif
    defaults:   { _controller: AdminBundle:AdminTarif:index }

tarif_add:
    path:     /admin/config/tarif/add
    defaults: { _controller: AdminBundle:AdminTarif:add }

tarif_delete:
    path:     /admin/config/tarif/delete
    defaults: { _controller: AdminBundle:AdminTarif:delete }

tarif_form:
    path:     /admin/config/tarif/form
    defaults: { _controller: AdminBundle:AdminTarif:form }

#Contact
admin_contact:
    path:       /admin/config/contact
    defaults:   { _controller: AdminBundle:AdminContact:index }

contact_add:
    path:     /admin/config/contact/add
    defaults: { _controller: AdminBundle:AdminContact:add }

contact_delete:
    path:     /admin/config/contact/delete
    defaults: { _controller: AdminBundle:AdminContact:delete }

contact_form:
    path:     /admin/config/contact/form
    defaults: { _controller: AdminBundle:AdminContact:form }
