admin_home:
    path:     /admin
    defaults: { _controller: AdminBundle:Admin:index }

admin_entity:
    path:       /admin/entity/{entity_type}
    defaults:   { _controller: AdminBundle:AdminEntity:index }

admin_entity_form:
    path:       /admin/entity/{entity_type}/form/{id}
    defaults:   { _controller: AdminBundle:AdminEntity:form }

admin_entity_save:
    path:       /admin/entity/{entity_type}/save
    defaults:   { _controller: AdminBundle:AdminEntity:save }

admin_entity_delete:
    path:       /admin/entity/{entity_type}/delete/{id}
    defaults:   { _controller: AdminBundle:AdminEntity:delete }

#Inscrit
admin_inscrit:
    path:       /admin/inscrit
    defaults:   { _controller: AdminBundle:AdminInscrit:index }

inscrit_add:
    path:     /admin/inscrit/add
    defaults: { _controller: AdminBundle:AdminInscrit:add }

inscrit_delete:
    path:     /admin/inscrit/delete
    defaults: { _controller: AdminBundle:AdminInscrit:delete }

inscrit_form:
    path:     /admin/inscrit/form
    defaults: { _controller: AdminBundle:AdminInscrit:form }
