services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    manager.admin:
        class: Bundle\AdminBundle\Manager\AdminManager
        arguments: ['@doctrine.orm.entity_manager']
