services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    manager.admin:
        class: Bundle\AdminBundle\Manager\AdminManager
        arguments: ['@doctrine.orm.entity_manager']

    manager.admin_actualite:
        class: Bundle\AdminBundle\Manager\AdminActualiteManager
        arguments: ['@doctrine.orm.entity_manager', '@session']

    manager.admin_course:
        class: Bundle\AdminBundle\Manager\AdminCourseManager
        arguments: ['@doctrine.orm.entity_manager', '@session']
